### ISSUE TITLE
Caching using the DefaultMemoryCache does not properly handle cache.RemoveStartWith

### ISSUE THREAD

**Issue by RobinHSanner** [filipw/Strathweb.CacheOutput#108]
RemoteStartsWith and Remove both do the same thing.

**Comment by micdenny** [comment]
but they should be called with different key, `RemoteStartsWith` is called to remove all the depending keys.

check the [Server side caching](https://github.com/filipw/AspNetWebApi-OutputCache#server-side-caching) section of the documentation:

> Each method can be cached multiple times separately - based on the representation (JSON, XML and so on). Therefore, CacheOutput will pass dependsOnKey value (which happens to be a prefix of all variations of a given cached method) when adding items to cache - this gives us flexibility to easily remove all variations of the cached method when we want to clear the cache. When cache gets invalidated, we will call RemoveStartsWith and just pass that key.

> The default cache store, System.Runtime.Caching.MemoryCache supports dependencies between cache items, so it's enough to just remove the main one, and all sub-dependencies get flushed. However, if you change the defalt implementation, and your underlying store doesn't - it's not a problem. When we invalidate cache (and need to cascade through all dependencies), we call RemoveStartsWith - so your custom store will just have to iterate through the entire store in the implementation of this method and remove all items with the prefix passed.

**Comment by dmalanij** [comment]
Just like @micdenny said. You can also check my answer in #182. Hope that helps
