### ISSUE TITLE
Invalidate Cache

### ISSUE THREAD

**Issue by spwizard** [filipw/Strathweb.CacheOutput#150]
I am using the  [InvalidateCacheOutput("Get", typeof(OtherController))] but I don't think its invalidating the cache.  Is there a method I can call to see all live caches.

Thanks Rob

**Comment by Jan-Olof** [comment]
We have the same experience. Works in 0.6 but not in 0.9.

**Comment by StephanyBatista** [comment]
Now I'm having the same problem. Sometime it works. Is anyone else having this problem?

**Comment by alexwiese** [comment]
Fixed by #162

**Comment by filipw** [comment]
this is now on nuget - https://www.nuget.org/packages/Strathweb.CacheOutput.WebApi2/0.10.0
