### ISSUE TITLE
Caching doesn't account for different users

### ISSUE THREAD

**Issue by cskiwi** [filipw/Strathweb.CacheOutput#163]
Hi

i'm using windows Auth in my application, and when a call is cached for one user, and another user requests that same call it returns the cached one, is there a way to say to the CacheOutput to take authentication in it's cache key

but This wouldn't have to be on all calls, just some

**Comment by nate-fr** [comment]
I'd strongly advise you to only cache calls that are not authentificated.

**Comment by nahidf** [comment]
default cache key generator doesn't support it, but you can customizing the cache keys per your requirement https://github.com/filipw/AspNetWebApi-OutputCache#customizing-the-cache-keys

**Comment by rolandocc** [comment]
Hi, is there any example on this? 

This is very useful in multi-tenant applications.
