### ISSUE TITLE
Question - Does this work properly with web farms?

### ISSUE THREAD

**Issue by dahlsailrunner** [filipw/Strathweb.CacheOutput#177]
We have two API servers in an F5-load-balanced web farm.  Let's say I have cached results on both web servers for a given API call, and then a POST gets processed by server A - which invalidates the cache based on the controller attribute.  If a new GET request comes in to server B, will it be a cached result or will it be (as I'm hoping) invalidated due to the POST on server A?

Thanks in advance for response.

**Comment by alexwiese** [comment]
By default it uses _System.Runtime.Caching.MemoryCache_ which only caches items in the memory of the local machine. If you want to use it in a web farm you will need an implementation of _IApiOutputCache_ that uses a shared cache such as [memcached ](https://memcached.org/).

**Comment by alexwiese** [comment]
Also there is an [implementation ](https://github.com/bymyslf/AspNetWebApi-OutputCache-Redis) that uses Redis.

**Comment by dahlsailrunner** [comment]
Thanks for the feedback -- that's what I was thinking.  And thanks for pointing out the Redis implementation.  I'll check that out for sure.
