### ISSUE TITLE
cache post response

### ISSUE THREAD

**Issue by slnksachin** [filipw/Strathweb.CacheOutput#179]
Is there any way to cache response from POST API
For security reasons we were asked to convert the query parameters passed, to convert into objects, which led us to convert our GET APIs to POST.
Let me know if there is a way to achieve this

**Comment by filipw** [comment]
You can subclass `CacheOutputAttribute` and override `IsCachingAllowed` method.
The default implementation only allows GET caching.

https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/CacheOutputAttribute.cs#L76

**Comment by slnksachin** [comment]
Thank you :+1:

**Comment by ibrahimozgon** [comment]
Hi @filipw, We can cache Post when we change IsCachingAllowed method. But Post body isn't considered in FormatParameters method. I think we should also override FormatParameters method?

**Comment by ibrahimozgon** [comment]
I changed DefaultCacheKeyGenerator class like this for trial. It works fine.
```
protected virtual string FormatParameters(HttpActionContext context, bool excludeQueryString)
{
    var actionParameters = context.ActionArguments.Where(x => x.Value != null).Select(x => x.Key + "=" + GetValue(x.Value));
    string parameters;
    if (!excludeQueryString)
    {
        parameters = PrepareGetParameters(context, actionParameters);
        if (context.Request.Method == HttpMethod.Post)
        {
            var postBody = context.Request.Content.ReadAsStringAsync().Result;
            var postParameters = JsonConvert.DeserializeObject<Dictionary<string, string>>(postBody, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                Formatting = Formatting.None,
                DefaultValueHandling = DefaultValueHandling.Ignore,
            });
            foreach (var param in postParameters)
            {
                if (!string.IsNullOrEmpty(param.Key) && !string.IsNullOrEmpty(param.Value))
                    parameters += param.Key.ToLower() + "=" + param.Value.ToLower() + "&";
            }
            parameters = parameters.TrimEnd('&');
        }
    }
    else
    {
        parameters = "-" + string.Join("&", actionParameters);
    }
    if (parameters == "-") parameters = string.Empty;
    return parameters;
}

private string PrepareGetParameters(HttpActionContext context, IEnumerable<string> actionParameters)
{
    var queryStringParameters =
        context.Request.GetQueryNameValuePairs()
            .Where(x => x.Key.ToLower() != "callback")
            .Select(x => x.Key + "=" + x.Value);
    var parametersCollections = actionParameters.Union(queryStringParameters);
    var parameters = ":" + string.Join("&", parametersCollections);
    var callbackValue = GetJsonpCallback(context.Request);
    if (!string.IsNullOrWhiteSpace(callbackValue))
    {
        var callback = "callback=" + callbackValue;
        if (parameters.Contains("&" + callback)) parameters = parameters.Replace("&" + callback, string.Empty);
        if (parameters.Contains(callback + "&")) parameters = parameters.Replace(callback + "&", string.Empty);
        if (parameters.Contains("-" + callback)) parameters = parameters.Replace("-" + callback, string.Empty);
        if (parameters.EndsWith("&")) parameters = parameters.TrimEnd('&');
    }
    return parameters;
}
```

**Comment by rogerabinader** [comment]
Hi @ibrahimozgon, i have tried implementing your DefaultCacheKeyGenerator, thank you so much for it.
However i am stuck at a level where
"var postBody = context.Request.Content.ReadAsStringAsync().Result;"
is empty.

My method is like this:

> 
        [HttpPost]
        [Route("filter")]
        [Route("filter/{pageIndex}")]
        [Route("filter/{pageIndex}/{pageSize}")]
        [CacheOutput(ServerTimeSpan = 10)]
        public List<ScheduleFull> Filter([FromBody]FilterOptions options, int pageSize = 51, int pageIndex = 0)
        {...}

where FilterOptions is a class containing criterias.
PrepareGetParameters is returning the following:
:options=CMACGM.SEA.Core.DTO.FilterOptions&pageSize=51&pageIndex=0
which i think is correct.

Any idea how to fix context.Request.Content.ReadAsStringAsync().Result;?

Else, what i did to unblock the situation for the time being, i used this block:

```
foreach (var param in context.ActionArguments)
                    {
                        if (!string.IsNullOrEmpty(param.Key))
                        {
                            parameters += param.Key.ToLower() + "=" + JsonConvert.SerializeObject(param.Value).ToLower() + "&";
                        }
                    }
                    parameters = parameters.TrimEnd('&');
```

Thank you so much,

**Comment by ibrahimozgon** [comment]
Hi @rogerabinader i opened a pull request and changed it.
Could you see: 
https://github.com/filipw/Strathweb.CacheOutput/pull/240/files
And  https://github.com/ibrahimozgon/Strathweb.CacheOutput/blob/7520397004c785660f2b42b478f4cb24c2c0642c/src/WebApi.OutputCache.V2/DefaultCacheKeyGenerator.cs

**Comment by rogerabinader** [comment]
@ibrahimozgon thank you so much for your help i really appreciate it. I'll try it out and get back to you. Thanks again.

**Comment by MstfTkrsln** [comment]
Hi @ibrahimozgon, @rogerabinader 

I have created my `MyCacheKeyGenerator `class ([which is ibrahim's version](https://github.com/ibrahimozgon/Strathweb.CacheOutput/blob/7520397004c785660f2b42b478f4cb24c2c0642c/src/WebApi.OutputCache.V2/DefaultCacheKeyGenerator.cs)) inherited from `ICacheKeyGenerator`.

Then i used this custom key generator in CacheOutputAttribute below.
```
    public class WebApiCacheAttribute: CacheOutputAttribute
    {
        public WebApiCacheAttribute()
        {
            CacheKeyGenerator = typeof(MyCacheKeyGenerator);
        }
        protected override bool IsCachingAllowed(HttpActionContext actionContext, bool anonymousOnly)
        {
            if (anonymousOnly)
            {
                if (Thread.CurrentPrincipal.Identity.IsAuthenticated)
                {
                    return false;
                }
            }

            if (actionContext.ActionDescriptor.GetCustomAttributes<IgnoreCacheOutputAttribute>().Any())
            {
                return false;
            }

            return actionContext.Request.Method == HttpMethod.Get || actionContext.Request.Method == HttpMethod.Post;
        }
    }
```

It works like a charm. 
Thanks.
