### ISSUE TITLE
Release new nuget package

### ISSUE THREAD

**Issue by dr-nsim** [filipw/Strathweb.CacheOutput#189]
Hello
Would you be so kind as to release a new nuget package based on the latest master?

**Comment by joth** [comment]
@filipw +1

**Comment by filipw** [comment]
done

 - https://github.com/filipw/Strathweb.CacheOutput/releases/tag/0.11.0
 - https://www.nuget.org/packages/Strathweb.CacheOutput.WebApi2/0.11.0
