### ISSUE TITLE
Why to call IApiOutputCache:Get method 4 times?

### ISSUE THREAD

**Issue by mchudinov** [filipw/Strathweb.CacheOutput#198]
Im using CacheOutput installed from NuGet package.
It calls 
`T Get<T>(string key) `
method from IApiOutputCache 4 times every time.
This is with only server side caching [CacheOutput(ServerTimeSpan = 60)]

Is one Get from cache not enough?

**Comment by dmalanij** [comment]
If you check the `CacheOutputAttribute` you'll understand why. The cache contains a few things related to the cached response and those are stored independently. Given the current implementation maybe this can be optimized to have 3 calls, but to only get one will need some refactor and might not be suitable for what @filipw has thought for the library (I guess having content, content type and etag as different keys aims to get this optimized for performance). Even more, thinking now about this, probably you'll always need to keep etag and content separated. 

Now: is this representing a problem for your implementation? I guess you're creating your own `IApiOutputCache` implementation. If your underlying caching system is good, reading a few extra values shouldn't be a significant overhead. 

Cheers
