### ISSUE TITLE
cacheOutputConfig.GetCacheOutputProvider System.NullReferenceException

### ISSUE THREAD

**Issue by joaocpribeiro** [filipw/Strathweb.CacheOutput#199]
I have an action in my API to clear the cache of another action.
It just does the following:

`public IHttpActionResult ClearCache()`
`{`
`var cacheOutputConfig = GlobalConfiguration.Configuration.CacheOutputConfiguration();`
`string key = cacheOutputConfig.MakeBaseCachekey((LanguageController c) => c.GetAll());`
`cacheOutputConfig.GetCacheOutputProvider(Request).Remove(key);`
`return Ok();`
`}`

It works fine, but now I would like to create some unit tests, just to make sure the action does not fail.

`[TestMethod]`
`public async Task ClearCache_Success()`
`{`
`    controller.Request = new System.Net.Http.HttpRequestMessage(System.Net.Http.HttpMethod.Get, new Uri("{my-url}"));`
`    var result = (await controller.ClearCache()) as OkResult;`
`    Assert.IsNotNull(result);`
`}`

When I run this test, I get a System.NullReferenceException "Object reference not set to an instance of an object.".
Here is the StackTrace:
> at System.Net.Http.HttpRequestMessageExtensions.GetDependencyScope(HttpRequestMessage request)
>    at WebApi.OutputCache.V2.CacheOutputConfiguration.GetCacheOutputProvider(HttpRequestMessage request)
>    {my test on this line: "cacheOutputConfig.GetCacheOutputProvider(Request).Remove(key);"}
> (...)

I believe the problem is in some property of the controller.Request, which was created manually, but which?

**Comment by joaocpribeiro** [comment]
I solved the problem creating a dummy instance of the dependency scope.
Once I am using [moq](https://github.com/moq/moq4), I did it like this:

`var dependencyResolverMock = new Mock<IDependencyResolver>();`
`var dependencyScopeMock = new Mock<IDependencyScope>();`
`dependencyResolverMock.Setup(dr => dr.BeginScope()).Returns(dependencyScopeMock.Object);`
`controller.Request.GetRequestContext().Configuration = new System.Web.Http.HttpConfiguration`
`{`
`DependencyResolver = dependencyResolverMock.Object`
`};`

**Comment by filipw** [comment]
👍
