### ISSUE TITLE
dynamicCompressionBeforeCache support?

### ISSUE THREAD

**Issue by gunnim** [filipw/Strathweb.CacheOutput#213]
Does your package honor dynamicCompressionBeforeCache  ?

If this flag is true do you cache the compressed response, saving on subsequent compressions?

More info on said setting here:
https://msdn.microsoft.com/en-us/library/aa347437(v=vs.90).aspx

**Comment by filipw** [comment]
No, these flags have nothing to do with this library - the flags you describe are for the built-in classic ASP.NET caching.
`Strathweb.CacheOutput`, just like entire Web API is not coupled to `web.config` or IIS or, for that matter, even the ASP.NET runtime, as it can run on other hosts too.
