### ISSUE TITLE
Wrong mediatype returned from the cache almost randomly

### ISSUE THREAD

**Issue by chialberto** [filipw/Strathweb.CacheOutput#216]
Hi,

I'm using the Cache for an API that returns images.
It works well for most of the time, but sometime it returns application/json mediatype instead images/jpeg although in the body the image is returned properly.
This looks to happens randomly, but the patterns seems to be when the cache is going to expire.
Is it possible that the the body cache entry expires a little bit after the mediatype one?
I'm using Redis, but the issue appears with memory caching too.

Any thought?

Regards,
Alberto

**Comment by chialberto** [comment]
Hi,
I made further investigation, if I remove the ":response-ct" key from the cache, a next call to my API returns the image but with type "application/json" in the header.
Is there any way for me to validate the consistency of the cache before returning the cached values?

Cheers,
Alberto

**Comment by chialberto** [comment]
Seems we found the problem, was on our code.
My apologies.
I don't know how to close/delete this issue.

**Comment by filipw** [comment]
great - thanks!
