### ISSUE TITLE
New release nuget package with fixes

### ISSUE THREAD

**Issue by mribichich** [filipw/Strathweb.CacheOutput#234]
Hi there, could you please release a new version with latest fixes?

Thanks!

**Comment by Jojoshua** [comment]
+1

**Comment by filipw** [comment]
done

 - https://github.com/filipw/Strathweb.CacheOutput/releases/tag/0.11.0
 - https://www.nuget.org/packages/Strathweb.CacheOutput.WebApi2/0.11.0
