### ISSUE TITLE
Inefficient workflow can cause huge delays in large application

### ISSUE THREAD

**Issue by stevozilik** [filipw/Strathweb.CacheOutput#62]
It is not entirely clear to me how to tell the framework to only do server side caching, or only do client side caching. Maybe an Enum propoperty on CacheOutputAttribute configuring that would do the job. If it's meant to be controlled by the Server and Client TimeSpans, then it's not working very well, here is why

In my scenario, I only want the client side caching:

 [CacheOutput(ClientTimeSpan = 59)]

however the implementation of CacheOutputAttribute is running a lot of initialization even if the ServerTimeSpan is <= 0. 

Specifically these two methods

EnsureCache(config, actionContext.Request);

var cacheKeyGenerator = config.CacheOutputConfiguration().GetCacheKeyGenerator(actionContext.Request, CacheKeyGenerator);

end up calling the DependencyResolver.GetDependencyScope().GetService(), which is unnecessary. 

The problem really stands out when using Unity, and the default implementation of Unity.WebApi.UnityDependencyResolver from Unity.WebAPI nuget package, that takes 100-200 mls to try to resolve the dependency, eventually failing anyway. 

executing all this code takes hundreds of milliseconds and significantly delays each call. When multiple calls, the delays rise linearly to seconds.

One could avoid all of this by refactiring the code in CacheOutputAttribute.OnActionExecuting(HttpActionContext actionContext) to:

 private void OnActionExecuting(HttpActionContext actionContext)
        {
            if (actionContext == null) throw new ArgumentNullException("actionContext");

```
        if (!_isCachingAllowed(actionContext, AnonymousOnly)) return;

        EnsureCacheTimeQuery();

        if (this.ServerTimeSpan <= 0)
            return;
```

.....

**Comment by dmalanij** [comment]
This is quite old, but I believe it can be closed. 
Check the current implementation of the `CacheOutputAttribute`
https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/CacheOutputAttribute.cs#L163

**Comment by filipw** [comment]
indeed
