### ISSUE TITLE
Client side caching not working with different languages

### ISSUE THREAD

**Issue by sarg3nt** [filipw/Strathweb.CacheOutput#96]
We have our content API returning different content for different languages.  The API differentiates the languages using the standard Accept-Language header.  
I have server caching working with a custom cache key generator that uses that header as part of the key, but this doesn't seem to do anything for client caching.
When I set a ClentTimeSpan of > 0 then the API starts returning the incorrect content.
It's really weird too.  It seems to return the correct content the first time we switch (first get) but then gets stuck on one language from there on out.
My conclusion, without digging into the source, is that whatever is setting caching for the client is not paying attention to the fact that the Accept-Language header is changing.
Is there a fix or do we just need to leave the client caching off?

**Comment by Gonkers** [comment]
I realize this issue is quite old, but can you use a custom `CacheKeyGenerator`? It worked out well for me. I set the current thread culture based on the Accept-Language header which allows me to cache separate languages.
```
    public class LocalizedCacheKeyGenerator : DefaultCacheKeyGenerator
    {
        public override string MakeCacheKey(HttpActionContext context, MediaTypeHeaderValue mediaType, bool excludeQueryString = false)
        {
            var cacheKey = base.MakeCacheKey(context, mediaType, excludeQueryString);
            cacheKey += "_" + Thread.CurrentThread.CurrentCulture.Name;
            return cacheKey;
        }
    }
```
You should also be able to access whatever headers you need through `context.ControllerContext.Request.Headers`
